### ISSUE TITLE
More DevKits

### ISSUE THREAD

**Issue by mottosso** [VictorYudin/saturn#1]
Hi @VictorYudin, I noticed in your README you were looking for devkits.

- Maya 2018 [win64](https://autodesk.box.com/shared/static/xuesav3biqnaxjgt87bemry9s9uy6og6), [osx](https://autodesk.box.com/shared/static/mln6fshe1uxwn0pqanu5p1nezmr5zb4b) & [linux](https://autodesk.box.com/shared/static/gloudjq6zljbg7br7o35vi82t158qcsd)

These are direct links that should work well in your automatic builds. I got them from here.

- Maya 2017 - https://apps.autodesk.com/MAYA/en/Detail/Index?id=6303159649350432165&appLang=en&os=Win64

**Comment by VictorYudin** [comment]
Hi @mottosso

Thanks for the info. Will update it.

**Comment by VictorYudin** [comment]
Thanks for the link. Maya 2018 plugin is available in the releases section.

**Comment by mottosso** [comment]
Thanks @VictorYudin, but are you sure VS 2017 is the right version to use with Maya 2018? I believe it might be 2015. It also appears as though USD only [officially support](https://github.com/PixarAnimationStudios/USD#dependencies) 2015.

Finally, possibly unrelated, but giving this a quick go tells me the version of USD View requires PySide, not PySide2 which is the flavour available in Maya 2017 and above.

```bash
$ cd usd
$ set PYTHONPATH=%cd%\lib\python
$ "c:\Program Files\Autodesk\Maya2018\bin"\mayapy.exe bin\usdview
Traceback (most recent call last):
  File "bin\usdview", line 28, in <module>
    import pxr.Usdviewq as Usdviewq
  File "C:\Users\marcus\Downloads\usd-v0.8.3.tar\usd\lib\python\pxr\Usdviewq\__init__.py", line 26, in <module>
    from qt import QtWidgets
  File "C:\Users\marcus\Downloads\usd-v0.8.3.tar\usd\lib\python\pxr\Usdviewq\qt.py", line 26, in <module>
    from attributeValueEditorUI import QtCore
  File "C:\Users\marcus\Downloads\usd-v0.8.3.tar\usd\lib\python\pxr\Usdviewq\attributeValueEditorUI.py", line 10, in <module>
    from PySide import QtCore, QtGui
ImportError: No module named PySide
```

Some quick surgery of `attributeValueEditorUI.py` from PySide to PySide2 reveals yet another issue.

```bash
Traceback (most recent call last):
  File "bin\usdview", line 28, in <module>
    import pxr.Usdviewq as Usdviewq
  File "C:\Users\marcus\Downloads\usd-v0.8.3.tar\usd\lib\python\pxr\Usdviewq\__init__.py", line 27, in <module>
    from common import Timer
  File "C:\Users\marcus\Downloads\usd-v0.8.3.tar\usd\lib\python\pxr\Usdviewq\common.py", line 26, in <module>
    from pxr import Tf, Sdf, Kind, Usd, UsdGeom, UsdShade
  File "C:\Users\marcus\Downloads\usd-v0.8.3.tar\usd\lib\python\pxr\Tf\__init__.py", line 85, in <module>
    from . import _tf
ImportError: DLL load failed: The specified module could not be found.
```

Which leads me to believe there is something either missing or built incorrectly.

**Comment by VictorYudin** [comment]
1) Yes, 2017 is good. It produces compatible objects.

2) I used PySide1 to compile the USD stuff, it means you can't use Maya 2018 environment to start `usdview`. Please look at the Python section of `appveyor.yml` to adjust Python environment:
```
    # Python
    - cmd: curl https://www.python.org/ftp/python/2.7.13/python-2.7.13.amd64.msi -o python.msi
    - cmd: msiexec /a python.msi /qb TARGETDIR=C:\projects\saturn\python
    - cmd: curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
    - cmd: python\python.exe get-pip.py
    - cmd: python\python.exe -m pip install PySide PyOpenGL Jinja2
```
Basically you need to get `pip` and install `PySide`, `PyOpenGL` and `Jinja2` using it. After this you can start `usdview` and other usd utils with following minimal environment:
```
set USD_INSTALL_ROOT=C:\usr\USD-0.8.3-2018-saturn
set PYTHONPATH=%PYTHONPATH%;%USD_INSTALL_ROOT%\lib\python
set PATH=%PATH%;%USD_INSTALL_ROOT%\lib;%USD_INSTALL_ROOT%\bin
"C:\Python27\python.exe" "%USD_INSTALL_ROOT%\bin\usdview" %*
```

3) USD for Maya 2018 also works well. You can look at the wiki to have an idea how to setup the environment.

**Comment by mottosso** [comment]
Thanks @VictorYudin!
