### ISSUE TITLE
Error on Release - 1.0.183 [USD v19.07] - Attached console output image

### ISSUE THREAD

**Issue by ghost** [VictorYudin/saturn#10]
![saturn-1 0 183_usd-19 07](https://user-images.githubusercontent.com/25729697/65613923-5f831e00-dfd4-11e9-920d-57b20a23bebb.JPG)

Tried with USD-18.11 as well. Same problems. Any help would be appreciated. Thanks!

**Comment by PixelPartner** [comment]
Try to add `%USD_INSTALL_ROOT%\lib\usd` to you System `%PATH%`

**Comment by grische** [comment]
@djdash are you using 32-bit windows or did you launch a 32-bit/x86 cmd.exe? Does the same happen if you use powershell (**not** the x86 version)?

If the above doesn't help, can you try USD 20.02 and see if this still happens?

**Comment by ghost** [comment]
@grische - solved with USD 20.02

Many thanks!
