### ISSUE TITLE
basic setup instructions

### ISSUE THREAD

**Issue by akeissami** [VictorYudin/saturn#2]
First, thank you so much for getting the build of USD working on Windows.

Apologies for the simple questions.  Would you please provide basic instructions on what I need to do to get it working on Windows?  What version of Python should I install?

I tried running usdview.cmd

Also, I tried to load the Maya plug-in pxrUsd.mll but get the following error:
// Error: file: C:/Program Files/Autodesk/Maya2018/scripts/others/pluginWin.mel line 905: Unable to dynamically load : C:/usd/third_party/maya/plugin/pxrUsd.mll
\usd\third_party\maya\plugin

Any guidance would be greatly appreciated.

**Comment by VictorYudin** [comment]
Hi,

I'm using the following script to set the Maya environment properly and
everything works well on my side. The environment is described here:
https://graphics.pixar.com/usd/docs/Maya-USD-Plugins.html

The script is:

@echo off

rem Edit following line to set the root of USD:
set USD_INSTALL_ROOT=C:\usr\USD-0.18.09-2018-saturn

set
MAYA_PLUG_IN_PATH=%MAYA_PLUG_IN_PATH%;%USD_INSTALL_ROOT%\third_party\maya\plugin
set
MAYA_SCRIPT_PATH=%MAYA_SCRIPT_PATH%;%USD_INSTALL_ROOT%\third_party\maya\share\
usd\plugins\usdMaya\resources
set PYTHONPATH=%PYTHONPATH%;%USD_INSTALL_ROOT%\lib\python
set XBMLANGPATH=%XBMLANGPATH%;%USD_INSTALL_ROOT%\third_party\maya\share\usd
\plugins\usdMaya\resources
set
PATH=%PATH%;%USD_INSTALL_ROOT%\lib;%USD_INSTALL_ROOT%\bin;%USD_INSTALL_ROOT%\third_party\maya\lib;%USD_INSTALL_ROOT%\..\boost\lib
"C:\Program Files\Autodesk\Maya2018\bin\maya.exe"

Best regards,
Victor

**Comment by VictorYudin** [comment]
Also, it's possible to use this attached file [usd.txt](https://github.com/VictorYudin/saturn/files/2363524/usd.txt). Just rename it to `usd.mod` and place it to `USD/third_party/maya` directory.

**Comment by AndrewJDR** [comment]
```
  express:router dispatching PUT /transactions/1332?access_token=xxx +15s
  express:router query  : /transactions/1332?access_token=xxx +1ms
  express:router expressInit  : /transactions/1332?access_token=xxx +1ms
  express:router jsonParser  : /transactions/1332?access_token=xxx +0ms
  body-parser:json content-type "application/json" +0ms
  body-parser:json content-encoding "identity" +1ms
  body-parser:json read body +0ms
  body-parser:json parse body +1ms
  body-parser:json parse json +0ms
  express:router logger  : /transactions/1332?access_token=xxx +0ms
Sep-29 07:32:05.543 [bot-sdk-Appservice] info: Processing transaction 1332
Sep-29 07:32:05.543 [bot-sdk-Appservice] info: Processing event of type m.room.message
Sep-29 07:32:05.546 [BotProvisioner] info: Got message to process with arg=setmatrixtoken
  morgan log request +12ms
127.0.0.1 - - [29/Sep/2019:07:32:05 +0000] "PUT /transactions/1332?access_token=xxx HTTP/1.1" 200 2 "-" "Synapse/1.3.1 (b=develop,ad64e90ed)"
  express:router dispatching PUT /transactions/1333?access_token=xxx +177ms
  express:router query  : /transactions/1333?access_token=xxx +0ms
  express:router expressInit  : /transactions/1333?access_token=xxx +1ms
  express:router jsonParser  : /transactions/1333?access_token=xxx +0ms
  body-parser:json content-type "application/json" +1ms
  body-parser:json content-encoding "identity" +0ms
  body-parser:json read body +1ms
  body-parser:json parse body +0ms
  body-parser:json parse json +1ms
  express:router logger  : /transactions/1333?access_token=xxx +0ms
Sep-29 07:32:05.736 [bot-sdk-Appservice] info: Processing transaction 1333
Sep-29 07:32:05.736 [bot-sdk-Appservice] info: Processing event of type m.room.message
  morgan log request +2ms
127.0.0.1 - - [29/Sep/2019:07:32:05 +0000] "PUT /transactions/1333?access_token=xxx HTTP/1.1" 200 2 "-" "Synapse/1.3.1 (b=develop,ad64e90ed)"
Sep-29 07:32:05.980 [bot-sdk-MatrixLiteClient] error: (REQ-1) { '0': '<',
  '1': '!',
  '2': 'D',
  '3': 'O',
  '4': 'C',
  '5': 'T',
  '6': 'Y',
  '7': 'P',
  '8': 'E',
  '9': ' ',
  '10': 'H',
  '11': 'T',
  '12': 'M',
  '13': 'L',
  '14': ' ',
  '15': 'P',
  '16': 'U',
...
  '295': '<',
  '296': '/',
  '297': 'h',
  '298': 't',
  '299': 'm',
  '300': 'l',
  '301': '>',
  '302': '\n' }
  express:router dispatching PUT /transactions/1334?access_token=xxx +488ms
  express:router query  : /transactions/1334?access_token=xxx +1ms
  express:router expressInit  : /transactions/1334?access_token=xxx +0ms
  express:router jsonParser  : /transactions/1334?access_token=xxx +1ms
  body-parser:json content-type "application/json" +0ms
  body-parser:json content-encoding "identity" +0ms
  body-parser:json read body +1ms
  body-parser:json parse body +1ms
  body-parser:json parse json +0ms
```
