### ISSUE TITLE
USD Animations sequences in Maya

### ISSUE THREAD

**Issue by videoprice** [VictorYudin/saturn#3]
Hello, how I can export/import animations from maya to USD file?
And any plan to update plugin for maya 2019 and arnold 3.1? 
thanks

**Comment by VictorYudin** [comment]
1) Regarding import/export, I think it's a question to the Pixar developers. https://groups.google.com/forum/#!forum/usd-interest
What about File->Import/Export?

2) Is Maya 2019 devkit available online?

3) What do you mean regarding Arnold? USD doesn't deal with it.
