### ISSUE TITLE
Can't find module _usd

### ISSUE THREAD

**Issue by jan-at-school** [VictorYudin/saturn#6]
```
from pxr import Usd, UsdGeom, Sdf, UsdShade, Gf, UsdSkel, Vt, Ar, UsdUtils
  File "C:\All Apps\usd-v18.11\usd\lib\python\pxr\Usd\__init__.py", line 24, in <module>
    import _usd
ModuleNotFoundError: No module named '_usd'
```

It seems like .pyd file should be built with the same python version. I tried with 2.7.10/15 and 3

**Comment by VictorYudin** [comment]
Hi,

It's built with Python 2.7.13. It doesn't work with Python 3. But most probably you have an issue in your environment. I added a small cmd file that sets everything up, so you can run USD stuff like this:
```
c:\usd\usd.cmd usdview c:\kitchen_set\Kitchen_set.usd
```

**Comment by jan-at-school** [comment]
Thank you for the help.. And yeah this was the issue.
It seems like we have add "path\to\usd-v18.11\usd\lib\" instead of "path\to\usd-v18.11\usd\lib\python" only.

Otherwise the module can't find the dll file. (The dll is present in the lib directory)
