### ISSUE TITLE
How to reduce build size? (Help plz)

### ISSUE THREAD

**Issue by jan-at-school** [VictorYudin/saturn#7]
Hey.

I have built usd on ubuntu using the build-script included in the official repository but the build size is very huge. How can I reduce it?
I see, you have 17 Mb tar ball.. min is about 300 Mb zip

Appreciate any help.. : )

**Comment by VictorYudin** [comment]
On Linux the libraries are bigger. I just checked the size of the Linux package built with Saturn, and it's a 380MB or a 40MB tarball.

**Comment by arifoo** [comment]
Hey.. appreciate it much :) 
I have managed to reduce it from over 1 GB to around 120 MB or so by blindly deleting the files not present in your build and it still works. 🙄😛
I will post the exact folders which I have deleted here today Inshallah.

**Comment by jan-at-school** [comment]
I just needed pxr module to use in gltf2usd It is working fine with the following files.
<pre><font color="#729FCF"><b>USDBUILD</b></font>
├── <font color="#729FCF"><b>bin</b></font>
├── <font color="#729FCF"><b>cmake</b></font>
├── <font color="#729FCF"><b>include</b></font>
│   └── <font color="#729FCF"><b>pxr</b></font>
│       ├── <font color="#729FCF"><b>base</b></font>
│       │   ├── <font color="#729FCF"><b>arch</b></font>
│       │   ├── <font color="#729FCF"><b>gf</b></font>
│       │   ├── <font color="#729FCF"><b>js</b></font>
│       │   ├── <font color="#729FCF"><b>plug</b></font>
│       │   ├── <font color="#729FCF"><b>tf</b></font>
│       │   ├── <font color="#729FCF"><b>trace</b></font>
│       │   ├── <font color="#729FCF"><b>vt</b></font>
│       │   └── <font color="#729FCF"><b>work</b></font>
│       ├── <font color="#729FCF"><b>imaging</b></font>
│       │   ├── <font color="#729FCF"><b>cameraUtil</b></font>
│       │   ├── <font color="#729FCF"><b>garch</b></font>
│       │   ├── <font color="#729FCF"><b>glf</b></font>
│       │   ├── <font color="#729FCF"><b>hd</b></font>
│       │   ├── <font color="#729FCF"><b>hdSt</b></font>
│       │   ├── <font color="#729FCF"><b>hdStream</b></font>
│       │   ├── <font color="#729FCF"><b>hdx</b></font>
│       │   ├── <font color="#729FCF"><b>hf</b></font>
│       │   └── <font color="#729FCF"><b>pxOsd</b></font>
│       ├── <font color="#729FCF"><b>usd</b></font>
│       │   ├── <font color="#729FCF"><b>ar</b></font>
│       │   ├── <font color="#729FCF"><b>kind</b></font>
│       │   ├── <font color="#729FCF"><b>ndr</b></font>
│       │   ├── <font color="#729FCF"><b>pcp</b></font>
│       │   ├── <font color="#729FCF"><b>sdf</b></font>
│       │   ├── <font color="#729FCF"><b>sdr</b></font>
│       │   ├── <font color="#729FCF"><b>usd</b></font>
│       │   ├── <font color="#729FCF"><b>usdGeom</b></font>
│       │   ├── <font color="#729FCF"><b>usdHydra</b></font>
│       │   ├── <font color="#729FCF"><b>usdLux</b></font>
│       │   ├── <font color="#729FCF"><b>usdRi</b></font>
│       │   ├── <font color="#729FCF"><b>usdShade</b></font>
│       │   ├── <font color="#729FCF"><b>usdSkel</b></font>
│       │   ├── <font color="#729FCF"><b>usdUI</b></font>
│       │   ├── <font color="#729FCF"><b>usdUtils</b></font>
│       │   └── <font color="#729FCF"><b>usdVol</b></font>
│       └── <font color="#729FCF"><b>usdImaging</b></font>
│           ├── <font color="#729FCF"><b>usdImaging</b></font>
│           ├── <font color="#729FCF"><b>usdImagingGL</b></font>
│           ├── <font color="#729FCF"><b>usdSkelImaging</b></font>
│           ├── <font color="#729FCF"><b>usdviewq</b></font>
│           └── <font color="#729FCF"><b>usdVolImaging</b></font>
├── <font color="#729FCF"><b>lib</b></font>
│   ├── <font color="#729FCF"><b>pkgconfig</b></font>
│   ├── <font color="#729FCF"><b>python</b></font>
│   │   └── <font color="#729FCF"><b>pxr</b></font>
│   │       ├── <font color="#729FCF"><b>Ar</b></font>
│   │       ├── <font color="#729FCF"><b>CameraUtil</b></font>
│   │       ├── <font color="#729FCF"><b>Garch</b></font>
│   │       ├── <font color="#729FCF"><b>Gf</b></font>
│   │       ├── <font color="#729FCF"><b>Glf</b></font>
│   │       ├── <font color="#729FCF"><b>Kind</b></font>
│   │       ├── <font color="#729FCF"><b>Ndr</b></font>
│   │       ├── <font color="#729FCF"><b>Pcp</b></font>
│   │       ├── <font color="#729FCF"><b>Plug</b></font>
│   │       ├── <font color="#729FCF"><b>Sdf</b></font>
│   │       ├── <font color="#729FCF"><b>Sdr</b></font>
│   │       ├── <font color="#729FCF"><b>Tf</b></font>
│   │       │   └── <font color="#729FCF"><b>testenv</b></font>
│   │       ├── <font color="#729FCF"><b>Trace</b></font>
│   │       ├── <font color="#729FCF"><b>Usd</b></font>
│   │       ├── <font color="#729FCF"><b>UsdGeom</b></font>
│   │       ├── <font color="#729FCF"><b>UsdHydra</b></font>
│   │       ├── <font color="#729FCF"><b>UsdImagingGL</b></font>
│   │       ├── <font color="#729FCF"><b>UsdLux</b></font>
│   │       ├── <font color="#729FCF"><b>UsdRi</b></font>
│   │       ├── <font color="#729FCF"><b>UsdSchemaExamples</b></font>
│   │       ├── <font color="#729FCF"><b>UsdShade</b></font>
│   │       ├── <font color="#729FCF"><b>UsdShaders</b></font>
│   │       ├── <font color="#729FCF"><b>UsdSkel</b></font>
│   │       ├── <font color="#729FCF"><b>UsdUI</b></font>
│   │       ├── <font color="#729FCF"><b>UsdUtils</b></font>
│   │       ├── <font color="#729FCF"><b>Usdviewq</b></font>
│   │       │   └── <font color="#729FCF"><b>icons</b></font>
│   │       ├── <font color="#729FCF"><b>UsdVol</b></font>
│   │       ├── <font color="#729FCF"><b>Vt</b></font>
│   │       └── <font color="#729FCF"><b>Work</b></font>
│   └── <font color="#729FCF"><b>usd</b></font>
│       ├── <font color="#729FCF"><b>ar</b></font>
│       │   └── <font color="#729FCF"><b>resources</b></font>
│       ├── <font color="#729FCF"><b>glf</b></font>
│       │   └── <font color="#729FCF"><b>resources</b></font>
│       │       └── <font color="#729FCF"><b>shaders</b></font>
│       ├── <font color="#729FCF"><b>hd</b></font>
│       │   └── <font color="#729FCF"><b>resources</b></font>
│       ├── <font color="#729FCF"><b>hdSt</b></font>
│       │   └── <font color="#729FCF"><b>resources</b></font>
│       │       └── <font color="#729FCF"><b>shaders</b></font>
│       ├── <font color="#729FCF"><b>hdx</b></font>
│       │   └── <font color="#729FCF"><b>resources</b></font>
│       │       └── <font color="#729FCF"><b>shaders</b></font>
│       ├── <font color="#729FCF"><b>ndr</b></font>
│       │   └── <font color="#729FCF"><b>resources</b></font>
│       ├── <font color="#729FCF"><b>sdf</b></font>
│       │   └── <font color="#729FCF"><b>resources</b></font>
│       ├── <font color="#729FCF"><b>usd</b></font>
│       │   └── <font color="#729FCF"><b>resources</b></font>
│       │       ├── <font color="#729FCF"><b>codegenTemplates</b></font>
│       │       └── <font color="#729FCF"><b>usd</b></font>
│       ├── <font color="#729FCF"><b>usdGeom</b></font>
│       │   └── <font color="#729FCF"><b>resources</b></font>
│       │       └── <font color="#729FCF"><b>usdGeom</b></font>
│       ├── <font color="#729FCF"><b>usdHydra</b></font>
│       │   └── <font color="#729FCF"><b>resources</b></font>
│       │       └── <font color="#729FCF"><b>shaders</b></font>
│       ├── <font color="#729FCF"><b>usdImaging</b></font>
│       │   └── <font color="#729FCF"><b>resources</b></font>
│       ├── <font color="#729FCF"><b>usdImagingGL</b></font>
│       │   └── <font color="#729FCF"><b>resources</b></font>
│       │       └── <font color="#729FCF"><b>shaders</b></font>
│       ├── <font color="#729FCF"><b>usdLux</b></font>
│       │   └── <font color="#729FCF"><b>resources</b></font>
│       │       └── <font color="#729FCF"><b>usdLux</b></font>
│       ├── <font color="#729FCF"><b>usdRi</b></font>
│       │   └── <font color="#729FCF"><b>resources</b></font>
│       │       └── <font color="#729FCF"><b>usdRi</b></font>
│       ├── <font color="#729FCF"><b>usdShade</b></font>
│       │   └── <font color="#729FCF"><b>resources</b></font>
│       │       └── <font color="#729FCF"><b>usdShade</b></font>
│       ├── <font color="#729FCF"><b>usdShaders</b></font>
│       │   └── <font color="#729FCF"><b>resources</b></font>
│       │       └── <font color="#729FCF"><b>shaders</b></font>
│       ├── <font color="#729FCF"><b>usdSkel</b></font>
│       │   └── <font color="#729FCF"><b>resources</b></font>
│       │       └── <font color="#729FCF"><b>usdSkel</b></font>
│       ├── <font color="#729FCF"><b>usdSkelImaging</b></font>
│       │   └── <font color="#729FCF"><b>resources</b></font>
│       ├── <font color="#729FCF"><b>usdUI</b></font>
│       │   └── <font color="#729FCF"><b>resources</b></font>
│       │       └── <font color="#729FCF"><b>usdUI</b></font>
│       ├── <font color="#729FCF"><b>usdVol</b></font>
│       │   └── <font color="#729FCF"><b>resources</b></font>
│       │       └── <font color="#729FCF"><b>usdVol</b></font>
│       └── <font color="#729FCF"><b>usdVolImaging</b></font>
│           └── <font color="#729FCF"><b>resources</b></font>
└── <font color="#729FCF"><b>plugin</b></font>
    └── <font color="#729FCF"><b>usd</b></font>
        └── <font color="#729FCF"><b>hdStream</b></font>
            └── <font color="#729FCF"><b>resources</b></font>
</pre>
