### ISSUE TITLE
Error when opening USD files

### ISSUE THREAD

**Issue by swamiforlife** [VictorYudin/saturn#8]
When i run the following command 
c:\usd\usd.cmd usdview c:\kitchen_set\Kitchen_set.usd
I get the following errors 
Warning: in Link at line 203 of C:\projects\saturn\build\USD\pxr\imaging\lib\hdSt\glslProgram.cpp -- Failed to link shader: Vertex shader(s) failed to link, fragment shader(s) failed to link.
Vertex link error: INVALID_OPERATION.

I don't have a folder named C:\projects\saturn\build\....
The scene opens in usdview but when i import usd files in maya i get many lines of errors with errors pointing to that path above.
Scene also opens in maya, so should i ignore those errors. 

What am i doing wrong?

**Comment by thewaylord** [comment]
i had a similar problem ...

**Comment by grische** [comment]
@swamiforlife does this still happen with USD 20.02?

**Comment by swamiforlife** [comment]
Works in USD 20.02
